name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"  # 缓存npm
       # 安装npm依赖
      - name: Installing Dependencies
        run: npm install --prefer-offline --no-audit # 优先使用离线缓存; 不审计
      # 运行代码扫描
      - name: Running Lint
        run: npm run lint # 自定义的eslint扫描; 允许warning
      # 构建
      - name: Building
        run: npm run build
  
  CD:
    needs: CI # 需要CI通过; 仅在CI成功后执行
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout repository
        uses: actions/checkout@v2
      # 给当前环境下载node
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      # 安装npm依赖
      - name: Installing Dependencies
        run: npm install --prefer-offline --no-audit # 优先使用离线缓存; 不审计
      # 构建
      - name: Building
        run: npm run build
      # 安装rsync传输工具
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      # 部署到服务器
      - name: Deploying to Server via SSH
        uses: appleboy/ssh-action@v1
        with:
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的所有文件
          # ARGS: "-avzr --delete" 
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          # SOURCE: "./dist/"
          host: ${{ secrets.REMOTE_HOST}}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            mkdir -p ${{ secrets.REMOTE_TARGET_PATH }}
            rsync -avzr --delete ./dist/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET_PATH }}

          